name: "GitHub Actions Workflow"
run-name: "${{ github.actor }} Workflow"

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display GITHUB_ACTIONS environment variable
        run: echo "GITHUB_ACTIONS=${{ env.GITHUB_ACTIONS }}"

      - name: Show branch name and repository
        run: echo "Repository is ${{ github.repository }}, Branch is ${{ github.head_ref }}"

      - name: Show the event that triggered the workflow
        run: echo "Event is ${{ github.event_name }}"
